title: Miguel Medina PatÃ³n # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/miguel-medina-a754a4191/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
